// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eUcionica.Services;

#nullable disable

namespace eUcionica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240731223947_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eUcionica.Models.Oblast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredmetID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PredmetID");

                    b.ToTable("Oblast");
                });

            modelBuilder.Entity("eUcionica.Models.Pitanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NivoTezine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OblastID")
                        .HasColumnType("int");

                    b.Property<string>("PitanjeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredmetID")
                        .HasColumnType("int");

                    b.Property<string>("TacanOdgovor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OblastID");

                    b.HasIndex("PredmetID");

                    b.ToTable("Pitanje");
                });

            modelBuilder.Entity("eUcionica.Models.Predmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NazivPredmeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Predmet");
                });

            modelBuilder.Entity("eUcionica.Models.Oblast", b =>
                {
                    b.HasOne("eUcionica.Models.Predmet", "Predmet")
                        .WithMany("Oblasti")
                        .HasForeignKey("PredmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("eUcionica.Models.Pitanje", b =>
                {
                    b.HasOne("eUcionica.Models.Oblast", "Oblast")
                        .WithMany("OblastPredmeta")
                        .HasForeignKey("OblastID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eUcionica.Models.Predmet", "Predmet")
                        .WithMany("Pitanja")
                        .HasForeignKey("PredmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oblast");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("eUcionica.Models.Oblast", b =>
                {
                    b.Navigation("OblastPredmeta");
                });

            modelBuilder.Entity("eUcionica.Models.Predmet", b =>
                {
                    b.Navigation("Oblasti");

                    b.Navigation("Pitanja");
                });
#pragma warning restore 612, 618
        }
    }
}
